package com.charms.user.dao.model;

import java.util.Date;

public class UserExtra {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_extra.uid
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_extra.vendor
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String vendor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_extra.client_name
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String clientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_extra.client_version
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String clientVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_extra.os_name
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String osName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_extra.os_version
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String osVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_extra.device_name
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String deviceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_extra.device_id
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_extra.idfa
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String idfa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_extra.idfv
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String idfv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_extra.market
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String market;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_extra.create_time
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_extra.update_time
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_extra.remove_status
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private Byte removeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_extra.extend1
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String extend1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_extra.extend2
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String extend2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_extra.extend3
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String extend3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_extra.uid
     *
     * @return the value of user_extra.uid
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_extra.uid
     *
     * @param uid the value for user_extra.uid
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_extra.vendor
     *
     * @return the value of user_extra.vendor
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public String getVendor() {
        return vendor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_extra.vendor
     *
     * @param vendor the value for user_extra.vendor
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setVendor(String vendor) {
        this.vendor = vendor == null ? null : vendor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_extra.client_name
     *
     * @return the value of user_extra.client_name
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public String getClientName() {
        return clientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_extra.client_name
     *
     * @param clientName the value for user_extra.client_name
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setClientName(String clientName) {
        this.clientName = clientName == null ? null : clientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_extra.client_version
     *
     * @return the value of user_extra.client_version
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public String getClientVersion() {
        return clientVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_extra.client_version
     *
     * @param clientVersion the value for user_extra.client_version
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setClientVersion(String clientVersion) {
        this.clientVersion = clientVersion == null ? null : clientVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_extra.os_name
     *
     * @return the value of user_extra.os_name
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public String getOsName() {
        return osName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_extra.os_name
     *
     * @param osName the value for user_extra.os_name
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setOsName(String osName) {
        this.osName = osName == null ? null : osName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_extra.os_version
     *
     * @return the value of user_extra.os_version
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public String getOsVersion() {
        return osVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_extra.os_version
     *
     * @param osVersion the value for user_extra.os_version
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setOsVersion(String osVersion) {
        this.osVersion = osVersion == null ? null : osVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_extra.device_name
     *
     * @return the value of user_extra.device_name
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public String getDeviceName() {
        return deviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_extra.device_name
     *
     * @param deviceName the value for user_extra.device_name
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName == null ? null : deviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_extra.device_id
     *
     * @return the value of user_extra.device_id
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_extra.device_id
     *
     * @param deviceId the value for user_extra.device_id
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_extra.idfa
     *
     * @return the value of user_extra.idfa
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public String getIdfa() {
        return idfa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_extra.idfa
     *
     * @param idfa the value for user_extra.idfa
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setIdfa(String idfa) {
        this.idfa = idfa == null ? null : idfa.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_extra.idfv
     *
     * @return the value of user_extra.idfv
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public String getIdfv() {
        return idfv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_extra.idfv
     *
     * @param idfv the value for user_extra.idfv
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setIdfv(String idfv) {
        this.idfv = idfv == null ? null : idfv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_extra.market
     *
     * @return the value of user_extra.market
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public String getMarket() {
        return market;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_extra.market
     *
     * @param market the value for user_extra.market
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setMarket(String market) {
        this.market = market == null ? null : market.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_extra.create_time
     *
     * @return the value of user_extra.create_time
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_extra.create_time
     *
     * @param createTime the value for user_extra.create_time
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_extra.update_time
     *
     * @return the value of user_extra.update_time
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_extra.update_time
     *
     * @param updateTime the value for user_extra.update_time
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_extra.remove_status
     *
     * @return the value of user_extra.remove_status
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public Byte getRemoveStatus() {
        return removeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_extra.remove_status
     *
     * @param removeStatus the value for user_extra.remove_status
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setRemoveStatus(Byte removeStatus) {
        this.removeStatus = removeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_extra.extend1
     *
     * @return the value of user_extra.extend1
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public String getExtend1() {
        return extend1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_extra.extend1
     *
     * @param extend1 the value for user_extra.extend1
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setExtend1(String extend1) {
        this.extend1 = extend1 == null ? null : extend1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_extra.extend2
     *
     * @return the value of user_extra.extend2
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public String getExtend2() {
        return extend2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_extra.extend2
     *
     * @param extend2 the value for user_extra.extend2
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setExtend2(String extend2) {
        this.extend2 = extend2 == null ? null : extend2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_extra.extend3
     *
     * @return the value of user_extra.extend3
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public String getExtend3() {
        return extend3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_extra.extend3
     *
     * @param extend3 the value for user_extra.extend3
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setExtend3(String extend3) {
        this.extend3 = extend3 == null ? null : extend3.trim();
    }
}