package com.charms.user.dao.model;

import java.util.Date;

public class UserBase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.uid
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.user_role
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private Integer userRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.register_source
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private Byte registerSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.user_name
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.nick_name
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.gender
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private Boolean gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.birthday
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private Long birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.signature
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String signature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.mobile
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.mobile_bind_time
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private Integer mobileBindTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.email
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.email_bind_time
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private Integer emailBindTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.face
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String face;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.face200
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String face200;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.srcface
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String srcface;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.create_time
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.update_time
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.remove_status
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private Byte removeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.push_token
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String pushToken;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.uid
     *
     * @return the value of user_base.uid
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.uid
     *
     * @param uid the value for user_base.uid
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.user_role
     *
     * @return the value of user_base.user_role
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public Integer getUserRole() {
        return userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.user_role
     *
     * @param userRole the value for user_base.user_role
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setUserRole(Integer userRole) {
        this.userRole = userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.register_source
     *
     * @return the value of user_base.register_source
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public Byte getRegisterSource() {
        return registerSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.register_source
     *
     * @param registerSource the value for user_base.register_source
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setRegisterSource(Byte registerSource) {
        this.registerSource = registerSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.user_name
     *
     * @return the value of user_base.user_name
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.user_name
     *
     * @param userName the value for user_base.user_name
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.nick_name
     *
     * @return the value of user_base.nick_name
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.nick_name
     *
     * @param nickName the value for user_base.nick_name
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.gender
     *
     * @return the value of user_base.gender
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public Boolean getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.gender
     *
     * @param gender the value for user_base.gender
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setGender(Boolean gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.birthday
     *
     * @return the value of user_base.birthday
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public Long getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.birthday
     *
     * @param birthday the value for user_base.birthday
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setBirthday(Long birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.signature
     *
     * @return the value of user_base.signature
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.signature
     *
     * @param signature the value for user_base.signature
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setSignature(String signature) {
        this.signature = signature == null ? null : signature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.mobile
     *
     * @return the value of user_base.mobile
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.mobile
     *
     * @param mobile the value for user_base.mobile
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.mobile_bind_time
     *
     * @return the value of user_base.mobile_bind_time
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public Integer getMobileBindTime() {
        return mobileBindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.mobile_bind_time
     *
     * @param mobileBindTime the value for user_base.mobile_bind_time
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setMobileBindTime(Integer mobileBindTime) {
        this.mobileBindTime = mobileBindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.email
     *
     * @return the value of user_base.email
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.email
     *
     * @param email the value for user_base.email
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.email_bind_time
     *
     * @return the value of user_base.email_bind_time
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public Integer getEmailBindTime() {
        return emailBindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.email_bind_time
     *
     * @param emailBindTime the value for user_base.email_bind_time
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setEmailBindTime(Integer emailBindTime) {
        this.emailBindTime = emailBindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.face
     *
     * @return the value of user_base.face
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public String getFace() {
        return face;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.face
     *
     * @param face the value for user_base.face
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setFace(String face) {
        this.face = face == null ? null : face.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.face200
     *
     * @return the value of user_base.face200
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public String getFace200() {
        return face200;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.face200
     *
     * @param face200 the value for user_base.face200
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setFace200(String face200) {
        this.face200 = face200 == null ? null : face200.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.srcface
     *
     * @return the value of user_base.srcface
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public String getSrcface() {
        return srcface;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.srcface
     *
     * @param srcface the value for user_base.srcface
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setSrcface(String srcface) {
        this.srcface = srcface == null ? null : srcface.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.create_time
     *
     * @return the value of user_base.create_time
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.create_time
     *
     * @param createTime the value for user_base.create_time
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.update_time
     *
     * @return the value of user_base.update_time
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.update_time
     *
     * @param updateTime the value for user_base.update_time
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.remove_status
     *
     * @return the value of user_base.remove_status
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public Byte getRemoveStatus() {
        return removeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.remove_status
     *
     * @param removeStatus the value for user_base.remove_status
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setRemoveStatus(Byte removeStatus) {
        this.removeStatus = removeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.push_token
     *
     * @return the value of user_base.push_token
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public String getPushToken() {
        return pushToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.push_token
     *
     * @param pushToken the value for user_base.push_token
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setPushToken(String pushToken) {
        this.pushToken = pushToken == null ? null : pushToken.trim();
    }
}