package com.charms.user.dao.model;

import java.math.BigDecimal;
import java.util.Date;

public class UserLocation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_location.uid
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_location.curr_nation
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String currNation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_location.curr_province
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String currProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_location.curr_city
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String currCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_location.curr_district
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String currDistrict;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_location.location
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_location.longitude
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private BigDecimal longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_location.latitude
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private BigDecimal latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_location.create_time
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_location.update_time
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_location.remove_status
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private Byte removeStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_location.uid
     *
     * @return the value of user_location.uid
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_location.uid
     *
     * @param uid the value for user_location.uid
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_location.curr_nation
     *
     * @return the value of user_location.curr_nation
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public String getCurrNation() {
        return currNation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_location.curr_nation
     *
     * @param currNation the value for user_location.curr_nation
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setCurrNation(String currNation) {
        this.currNation = currNation == null ? null : currNation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_location.curr_province
     *
     * @return the value of user_location.curr_province
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public String getCurrProvince() {
        return currProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_location.curr_province
     *
     * @param currProvince the value for user_location.curr_province
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setCurrProvince(String currProvince) {
        this.currProvince = currProvince == null ? null : currProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_location.curr_city
     *
     * @return the value of user_location.curr_city
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public String getCurrCity() {
        return currCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_location.curr_city
     *
     * @param currCity the value for user_location.curr_city
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setCurrCity(String currCity) {
        this.currCity = currCity == null ? null : currCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_location.curr_district
     *
     * @return the value of user_location.curr_district
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public String getCurrDistrict() {
        return currDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_location.curr_district
     *
     * @param currDistrict the value for user_location.curr_district
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setCurrDistrict(String currDistrict) {
        this.currDistrict = currDistrict == null ? null : currDistrict.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_location.location
     *
     * @return the value of user_location.location
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_location.location
     *
     * @param location the value for user_location.location
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_location.longitude
     *
     * @return the value of user_location.longitude
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_location.longitude
     *
     * @param longitude the value for user_location.longitude
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_location.latitude
     *
     * @return the value of user_location.latitude
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_location.latitude
     *
     * @param latitude the value for user_location.latitude
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_location.create_time
     *
     * @return the value of user_location.create_time
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_location.create_time
     *
     * @param createTime the value for user_location.create_time
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_location.update_time
     *
     * @return the value of user_location.update_time
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_location.update_time
     *
     * @param updateTime the value for user_location.update_time
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_location.remove_status
     *
     * @return the value of user_location.remove_status
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public Byte getRemoveStatus() {
        return removeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_location.remove_status
     *
     * @param removeStatus the value for user_location.remove_status
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setRemoveStatus(Byte removeStatus) {
        this.removeStatus = removeStatus;
    }
}