package com.charms.user.dao.model;

import lombok.Data;

import java.util.Date;

@Data
public class UserExtra {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_extra.uid
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_extra.vendor
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String vendor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_extra.client_name
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String clientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_extra.client_version
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String clientVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_extra.os_name
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String osName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_extra.os_version
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String osVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_extra.device_name
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String deviceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_extra.device_id
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_extra.idfa
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String idfa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_extra.idfv
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String idfv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_extra.market
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String market;


    private Date createTime;

    private Date updateTime;

    /**
     * 删除状态
     */
    private Byte removeStatus;

    private String extend1;

    /**
     * 扩展字段
     */
    private String extend2;

    /**
     * 扩展字段
     */
    private String extend3;


}