package com.charms.user.dao.model;

import lombok.Data;

import java.util.Date;

@Data
public class UserAuth {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.id
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.uid
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.identity_type
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private Byte identityType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.identifier
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String identifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.certificate
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String certificate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.create_time
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.update_time
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.remove_status
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private Byte removeStatus;

}