package com.charms.user.dao.model;

import java.util.Date;

public class UserLoginLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.id
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.uid
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.type
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.command
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private Byte command;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.version
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.client
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String client;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.device_id
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.lastip
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String lastip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.os
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String os;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.osver
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String osver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.text
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.create_time
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.update_time
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.remove_status
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    private Byte removeStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.id
     *
     * @return the value of user_login_log.id
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.id
     *
     * @param id the value for user_login_log.id
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.uid
     *
     * @return the value of user_login_log.uid
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.uid
     *
     * @param uid the value for user_login_log.uid
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.type
     *
     * @return the value of user_login_log.type
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.type
     *
     * @param type the value for user_login_log.type
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.command
     *
     * @return the value of user_login_log.command
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public Byte getCommand() {
        return command;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.command
     *
     * @param command the value for user_login_log.command
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setCommand(Byte command) {
        this.command = command;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.version
     *
     * @return the value of user_login_log.version
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.version
     *
     * @param version the value for user_login_log.version
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.client
     *
     * @return the value of user_login_log.client
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public String getClient() {
        return client;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.client
     *
     * @param client the value for user_login_log.client
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setClient(String client) {
        this.client = client == null ? null : client.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.device_id
     *
     * @return the value of user_login_log.device_id
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.device_id
     *
     * @param deviceId the value for user_login_log.device_id
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.lastip
     *
     * @return the value of user_login_log.lastip
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public String getLastip() {
        return lastip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.lastip
     *
     * @param lastip the value for user_login_log.lastip
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setLastip(String lastip) {
        this.lastip = lastip == null ? null : lastip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.os
     *
     * @return the value of user_login_log.os
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public String getOs() {
        return os;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.os
     *
     * @param os the value for user_login_log.os
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setOs(String os) {
        this.os = os == null ? null : os.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.osver
     *
     * @return the value of user_login_log.osver
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public String getOsver() {
        return osver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.osver
     *
     * @param osver the value for user_login_log.osver
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setOsver(String osver) {
        this.osver = osver == null ? null : osver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.text
     *
     * @return the value of user_login_log.text
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.text
     *
     * @param text the value for user_login_log.text
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.create_time
     *
     * @return the value of user_login_log.create_time
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.create_time
     *
     * @param createTime the value for user_login_log.create_time
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.update_time
     *
     * @return the value of user_login_log.update_time
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.update_time
     *
     * @param updateTime the value for user_login_log.update_time
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.remove_status
     *
     * @return the value of user_login_log.remove_status
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public Byte getRemoveStatus() {
        return removeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.remove_status
     *
     * @param removeStatus the value for user_login_log.remove_status
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    public void setRemoveStatus(Byte removeStatus) {
        this.removeStatus = removeStatus;
    }
}