package com.charms.user.dao.mapper;

import com.charms.user.dao.model.UserExtra;
import java.util.List;

public interface UserExtraMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_extra
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    int deleteByPrimaryKey(Long uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_extra
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    int insert(UserExtra record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_extra
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    UserExtra selectByPrimaryKey(Long uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_extra
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    List<UserExtra> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_extra
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    int updateByPrimaryKey(UserExtra record);
}