package com.charms.user.dao.mapper;

import com.charms.user.dao.model.UserLocation;
import java.util.List;

public interface UserLocationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_location
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    int deleteByPrimaryKey(Long uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_location
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    int insert(UserLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_location
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    UserLocation selectByPrimaryKey(Long uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_location
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    List<UserLocation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_location
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    int updateByPrimaryKey(UserLocation record);
}