package com.charms.user.dao.mapper;

import com.charms.user.dao.model.UserBase;
import java.util.List;

public interface UserBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    int deleteByPrimaryKey(Long uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    int insert(UserBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    UserBase selectByPrimaryKey(Long uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    List<UserBase> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    int updateByPrimaryKey(UserBase record);
}