package com.charms.user.dao.mapper;

import com.charms.user.dao.model.UserAuth;
import java.util.List;

public interface UserAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    int insert(UserAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    UserAuth selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    List<UserAuth> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbggenerated Mon Jan 01 16:18:15 CST 2018
     */
    int updateByPrimaryKey(UserAuth record);
}